public class test4 
{ 
     public static void main (String arg[])
    { int a={1,2,3,4,5}; 
    try{ System.out.println(" my exception"+a[5]); 
    } 
catch (Exception e)
{ System.out.println(e); 
} 
}
}